config/routes.rb
Music::Application.routes.draw do
  resources :bands
  resources :artists
  resources :albums
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :band_id

  belongs_to :band
  has_many :recordings

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true, :length => { :minimum => 1 },
    :uniqueness => { :scope => :name }

  has_many :authored_songs, :class_name => 'Song'
  has_many :band_artists, :foreign_key => :artist_id
  has_many :bands, :through => :band_artists
  has_many :albums, :through => :bands
  has_many :performed_songs, :through => :band_artists, :source => :recordings,
    :foreign_key => :recording_id
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true, :uniqueness => { :scope => :name }

  has_many :band_artists, :foreign_key => :band_id
  has_many :artists, :through => :band_artists
  has_many :recordings
  has_many :albums
end

app/models/band_artist.rb
class BandArtist < ActiveRecord::Base
  attr_accessible :band_id, :artist_id

  # validates :artist_id, :pre

  belongs_to :band
  belongs_to :artist
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  attr_accessible :song_id, :album_id, :band_id

  belongs_to :song
  belongs_to :album
  belongs_to :band
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :name, :artist_id

  belongs_to :artist
  has_many :recordings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all

  end

  def new

  end

  def create
    name = params[:artist][:name]
    artist = Artist.create(:name => name)
    band = Band.find(params[:artist][:band])

    BandArtist.create(:band_id => band.id, :artist_id => artist.id)
    redirect_to edit_band_path(band.id)
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
  end

  def destroy
    @artist = Artist.find(params[:id])
  end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    b = Band.new
    b.name = params[:name]
    if b.save
      redirect_to bands_path
    else
      render 'new'
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @artist = Artist.new
    @band = Band.find(params[:id])
    if @band.artists.empty?
      @possible_new_artists = Artist.all
    else
      @possible_new_artists = Artist.all.select! do |artist|
        !@band.artists.include?(artist)
      end
    end
  end

  def update
    b = Band.find(params[:id])
    if params[:band]
      b.name = params[:band][:name]
    end
    b.save

    if params[:artists]
      a = Artist.find(params[:artists][:artist_id])
      b.artists << a
    end
    if params[:deleted]
      d = Artist.find(params[:deleted][:artist_id])
      b.artists.delete(d)
    end

     redirect_to edit_band_path(b)
  end

  def destroy

    band = Band.find(params[:id])
    band.recordings.each { |recording| recording.destroy }
    band.artists.each { |member| member.destroy }
    band.albums.each { |album| album.destroy }
    band.destroy

    redirect_to bands_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/artists/index.html.erb
<h1>Welcome to the Glamorous BK Records</h1>
<h2>Our Artists</h2>
  <ul>
  <% @artists.each do |artist| %>
  <li>  <%= link_to artist.name, artist_path(artist) %></li>
    <% end %>
  </ul>

<%= link_to "Create A New Artist", new_artist_path %>
<br>
<%= link_to "Our Bands", bands_path %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<h2>Bands</h2>
  <ul>
    <% @artist.bands.each do |band| %>
    <li>
      <%= link_to band.name, band_path(band) %>
    </li>
    <% end %>
  </ul>

<h2>Albums</h2>
  <ul>
    <% @artist.albums.each do |album| %>
    <li>
      <% a = Album.find(album) %>
      <% b = Band.find(a.band_id) %>
      <%= link_to b.name, band_path(b) %>,
      <%= link_to a.name, album_path(a) %>
    </li>
    <% end %>
  </ul>

<h2>Authored Songs</h2>

<h2>Performed Songs</h2>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>
<%= form_for @band do |f| %>

<%= f.label :name, "Band Name:" %>
<%= f.text_field :name %>
<%= f.submit "Save!" %>
<% end %>

<h3>Add New Artist</h3>
<%= form_for @artist, :url => { :action => "create", :controller => "artists"} do |f| %>

<%= f.label :name, "Artists:" %>
<%= f.hidden_field :band, :value => @band.id %>
<%= f.text_field :name %>
<%= f.submit "Add Member!" %>
<% end %>

<h3>Add Existing Artist</h3>
<%= form_tag("/bands/#{@band.id}", :method => :put) do %>
<%= label_tag("Artists:") %>
<%= collection_select(:artists, :artist_id, @possible_new_artists, :id, :name) %>
<%= submit_tag("Add Member!") %>
<% end %>

<h3>Remove Artist</h3>
<%= form_tag("/bands/#{@band.id}", :method => :put) do %>
<%= label_tag("Members:") %>
<%= collection_select(:deleted, :artist_id, @band.artists, :id, :name) %>
<%= submit_tag("Abandon Member!") %>
<% end %>

<h3>Band Members</h3>
  <ul>
  <% @band.artists.each do |artist_id| %>
    <li>
      <%= Artist.find(artist_id).name %>
    </li>
  <% end %>
  </ul>
<%= link_to "Band Page", band_path(@band) %>

app/views/bands/index.html.erb
<h1>Welcome to the Glamorous BK Records</h1>
<h2>Our Bands</h2>
  <ul>
  <% @bands.each do |band| %>
  <li>  <%= link_to band.name, band_path(band) %></li>
    <% end %>
  </ul>


<%= link_to "Create A New Band", new_band_path %>

<br>
<%= link_to "Our Artists", artists_path %>

app/views/bands/new.html.erb
<h1> Create A New Band! </h1>
<%= form_tag('/bands', :method => :post) do %>

<%= label_tag("Band Name:") %>
<%= text_field_tag(:name) %>

<%= submit_tag("Rock Out!") %>
<% end %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h2>Members</h2>
  <ul>
    <% @band.artists.each do |artist_id| %>
      <li>
        <%= link_to Artist.find(artist_id).name, artist_path(Artist.find(artist_id)) %>
      </li>
    <% end %>
  </ul>
<h2>Albums</h2>
  <ul>
    <% @band.albums.each do |album| %>
      <li>
        <%= album.name %>
        <ol>
          <% album.recordings.each do |recording| %>
            <li>
              <%= Song.find(recording.song_id).name %>
            </li>
          <% end %>
        </ol>
      </li>
    <% end %>
  </ul>
<%= link_to "Edit", edit_band_path(@band) %>
<%= link_to "Destroy", band_path(@band), :confirm => "Are you sure? You will never hear this band again.", :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>